# Pure Storage SE Lab Melbourne - Shared Configuration
# This is the master configuration file for all lab infrastructure

lab_info:
  name: "Melbourne_SE_Lab"
  location: "Melbourne_Australia"
  contact: "prosham@purestorage.com"
  version: "1.0.0"
  created: "2025-07-30"
  description: "Pure Storage SE Lab Melbourne - Centralized Configuration"
  organization: "prosham-purestorage"

infrastructure:
  vcenter:
    server: "pstg-mgmt-vcsa1.mel.aulab.purestorage.com"
    datacenter: "Melbourne-SE-Lab"
    cluster: "567CollinsSt"
    datastore: "Pure-Mgmt-Local-SSD1"
    network: "MgmtDPG"
    template_folder: "Templates"
    content_library: "mel-au-lab"

# Domain Configuration Update for lab-config.yml
# Add this to the infrastructure.domain section

  domain:
    name: "mel.aulab.purestorage.com"
    ldap_url: "ldaps://pstg-mgmt-ad1.mel.aulab.purestorage.com:389"
    search_base: "dc=mel,dc=aulab,dc=purestorage,dc=com"
    bind_dn: "cn=purebind@mel.aulab.purestorage.com"
    
    # Domain Group Access Configuration
    # These groups control who can authenticate to Ubuntu templates
    allowed_groups:
      - "Domain Admins"
      - "Domain Users"
    
    # Groups that get administrative privileges (sudo access)
    admin_groups:
      - "Domain Admins"
    
    # Groups allowed for SSH access
    ssh_allowed_groups:
      - "ubuntu"      # Local ubuntu user
      - "sudo"        # Local sudo group
      - "Domain Admins"
      - "Domain Users"

# This will generate the following environment variables:
# INFRASTRUCTURE_DOMAIN_ALLOWED_GROUPS=Domain Admins,Domain Users
# INFRASTRUCTURE_DOMAIN_ADMIN_GROUPS=Domain Admins  
# INFRASTRUCTURE_DOMAIN_SSH_ALLOWED_GROUPS=ubuntu,sudo,Domain Admins,Domain Users  

  network:
    # Management Network Configuration
    management:
      port_group: "VMnetDPG"
      subnet: "10.211.0.0/24"
      gateway: "10.211.0.1"
      dns_servers:
        - "10.112.0.9"
      ntp_server: "10.98.0.2,10.98.0.3"
    
    # Storage Network Configuration  
    storage:
      port_group: "StorageDPG"
      subnet: "10.212.0.0/24"
      gateway: "10.212.0.1"
      # Storage networks typically use different DNS or no DNS
      dns_servers: []
    
    # Template Configuration Options
    template_config:
      default_type: "SingleHomed"  # SingleHomed or DualHomed
      dhcp_enabled: true
      adapter_type: "vmxnet3"
      
      # Static IP Configuration for Single-Homed Templates
      static_ip:
        enabled: false  # Set to true to use static IP instead of DHCP
        ip_range_start: "10.112.0.200"  # Starting IP for static assignments
        ip_range_end: "10.112.0.150"    # Ending IP for static assignments
        netmask: "255.255.255.0"
        default_static_ip: "10.112.0.200"  # Default static IP for admin template
      
    # Legacy compatibility (maintained for existing scripts)
    subnet: "10.112.0.0/24"
    gateway: "10.112.0.1"
    dns_servers:
      - "10.112.0.9"
    ntp_server: "10.98.0.2,10.98.0.3"
    
services:
  web_console:
    port: 3000
    ssl_enabled: true
    admin_vm_ip: "10.112.0.11"
    admin_vm_hostname: "pstg-mgmt-admin"
    repository: "prosham-purestorage/se-lab-melau-webconsole"
    
  rds:
    server_ip: "10.112.0.10"
    gateway_host: "pstg-mgmt-rds.mel.aulab.purestorage.com"
    web_access_url: "https://pstg-mgmt-rds.mel.aulab.purestorage.com/rdweb"
    farm_name: "Pure-SE-Lab-RDS"

vm_templates:
  ubuntu:
    template_name: "pr-ubuntu-template"
    base_image: "Ubuntu 22.04 LTS"
    cpu_cores: 2
    memory_gb: 4
    disk_gb: 20
    network: "VM Network"
    repository: "prosham-purestorage/se-lab-melau-vmtemplates"
    
    # Network Configuration Options
    network_configurations:
      single_homed:
        name_suffix: "single-net"
        primary_network: "VMnetDPG"
        description: "Single network adapter for management traffic only"
        use_cases: ["development", "testing", "simple deployments"]
        
        # IP Configuration Options
        ip_config:
          dhcp_enabled: true  # Default to DHCP
          static_ip_support: true
          static_ip_range:
            start: "10.112.0.100"
            end: "10.112.0.150"
          default_static_ip: "10.112.0.100"  # For admin template
          netmask: "255.255.255.0"
          
      dual_homed:
        name_suffix: "dual-net"
        primary_network: "VMnetDPG"      # Management network
        secondary_network: "StorageDPG"   # Storage network  
        description: "Dual network adapters for management and storage separation"
        use_cases: ["production", "storage systems", "performance testing"]
        
        # IP Configuration Options
        ip_config:
          management_dhcp: true  # Management network uses DHCP
          storage_dhcp: true     # Storage network uses DHCP
          # Static IP support available if needed
          static_ip_support: true
        
    # Template Variants by Ubuntu Version
    variants:
      ubuntu_20_04:
        base_image: "Ubuntu 20.04 LTS"
        support_level: "maintenance"
      ubuntu_22_04:
        base_image: "Ubuntu 22.04 LTS"
        support_level: "active"
      ubuntu_24_04:
        base_image: "Ubuntu 24.04 LTS"
        support_level: "active"
      
  windows_server:
    template_name: "pr-windows-server-template" 
    base_image: "Windows Server 2022"
    cpu_cores: 4
    memory_gb: 8
    disk_gb: 60
    network: "VM Network"
    repository: "prosham-purestorage/se-lab-melau-vmtemplates"
      
  windows_client:
    template_name: "pr-windows-client-template"
    base_image: "Windows 11 Enterprise"
    cpu_cores: 2
    memory_gb: 8
    disk_gb: 60
    network: "VM Network"
    repository: "prosham-purestorage/se-lab-melau-vmtemplates"

integration:
  repositories:
    config: "https://github.com/prosham-purestorage/se-lab-melau-config"
    webconsole: "https://github.com/prosham-purestorage/se-lab-melau-webconsole"
    vmtemplates: "https://github.com/prosham-purestorage/se-lab-melau-vmtemplates"
    ansible: "https://github.com/prosham-purestorage/se-lab-melau-ansible"
    
  shared_secrets:
    encryption_method: "aes-256-cbc"
    keyfile_location: "$HOME/.purestorage/se-lab-melau.key"
    secrets_file: "secrets.yml.encrypted"

pure_storage:
  arrays:
    primary:
      management_vip: "10.112.0.5"
      username: "pureuser"

security:
  ssl_certificates:
    path: "/opt/vmware-webconsole/certificates"
    auto_renew: true
  
  session:
    timeout_minutes: 480
    max_concurrent: 10

monitoring:
  log_level: "info"
  retention_days: 30