# Pure Storage SE Lab Melbourne - Shared Configuration
# This is the master configuration file for all lab infrastructure

lab_info:
  name: "Melbourne_SE_Lab"
  location: "Melbourne_Australia"
  contact: "prosham@purestorage.com"
  version: "1.0.0"
  created: "2025-07-30"
  description: "Pure Storage SE Lab Melbourne - Centralized Configuration"
  organization: "prosham-purestorage"

infrastructure:
  vcenter:
    server: "pstg-mgmt-vcsa1.mel.aulab.purestorage.com"
    datacenter: "Melbourne-SE-Lab"
    cluster: "567CollinsSt"
    datastore: "pstg-vmfs-01"
    network: "MgmtDPG"
    template_folder: "pstg-template"
    content_library: "mel-au-lab"

# Domain Configuration Update for lab-config.yml
# Add this to the infrastructure.domain section

  domain:
    name: "mel.aulab.purestorage.com"
    ldap_url: "ldaps://pstg-mgmt-ad1.mel.aulab.purestorage.com:389"
    search_base: "dc=mel,dc=aulab,dc=purestorage,dc=com"
    bind_dn: "cn=purebind@mel.aulab.purestorage.com"
    
    # Domain Group Access Configuration
    # These groups control who can authenticate to Ubuntu templates
    allowed_groups:
      - "PureSEs"
      - "PureGuests"
    
    # Groups that get administrative privileges (sudo access)
    admin_groups:
      - "PureSEs"

    # Groups allowed for SSH access
    ssh_allowed_groups:
      - "ubuntu"      # Local ubuntu user
      - "sudo"        # Local sudo group
      - "PureSEs"
      - "PureGuests"

# This will generate the following environment variables:
# INFRASTRUCTURE_DOMAIN_ALLOWED_GROUPS=Domain Admins,Domain Users
# INFRASTRUCTURE_DOMAIN_ADMIN_GROUPS=Domain Admins  
# INFRASTRUCTURE_DOMAIN_SSH_ALLOWED_GROUPS=ubuntu,sudo,Domain Admins,Domain Users  

  network:
    # Management Network Configuration
    management:
      port_group: "VMnetDPG"
      subnet: "10.211.0.0/24"
      gateway: "10.211.0.1"
      dns_servers:
        - "10.112.0.9"
      ntp_server: "10.98.0.2,10.98.0.3"
    
    # Storage Network Configuration  
    storage:
      port_group: "StorageDPG"
      subnet: "10.212.0.0/24"
      gateway: "10.212.0.1"
      # Storage networks typically use different DNS or no DNS
      dns_servers: []
    
    # Template Configuration Options
    template_config:
      default_type: "SingleHomed"  # SingleHomed or DualHomed
      dhcp_enabled: true          # Templates default to DHCP
      adapter_type: "vmxnet3"
      static_capable: true        # Templates support static IP at deployment time
      
    # Legacy compatibility (maintained for existing scripts)
    subnet: "10.112.0.0/24"
    gateway: "10.112.0.1"
    dns_servers:
      - "10.112.0.9"
    ntp_server: "10.98.0.2,10.98.0.3"

# Certificate Authority Configuration
certificates:
  ca_bundle:
    path: "certificates/ca_bundle.cer"
    description: "Combined CA certificate bundle for all lab services"
    
  pure_storage_ca:
    path: "certificates/keyfactor-purestorage.cer"
    description: "Pure Storage Keyfactor PKI Infrastructure Certificate"
    issuer: "PURE_STORAGE-RCA"
    valid_until: "2032-01-11"
    
  lab_ad_ca:
    path: "certificates/mel-au-ad-certsrv.cer"
    description: "Melbourne Lab Active Directory Certificate Services CA"
    issuer: "mel-PSTG-MGMT-AD1-CA-1"
    valid_until: "2033-07-31"
    
  installation:
    ubuntu_command: "sudo cp certificates/*.cer /usr/local/share/ca-certificates/ && sudo update-ca-certificates"
    centos_command: "sudo cp certificates/*.cer /etc/pki/ca-trust/source/anchors/ && sudo update-ca-trust"
    windows_command: "Import-Certificate -FilePath certificates\\*.cer -CertStoreLocation Cert:\\LocalMachine\\Root"
    
services:
  web_console:
    port: 3000
    ssl_enabled: true
    admin_vm_ip: "10.112.0.10"
    admin_vm_hostname: "pstg-mgmt-webconsole"
    repository: "prosham-purestorage/se-lab-melau-webconsole"
    
  rds:
    server_ip: "10.211.0.10"
    gateway_host: "pstg-mgmt-winrds.mel.aulab.purestorage.com"
    web_access_url: "https://pstg-mgmt-rds.mel.aulab.purestorage.com/rdweb"
    farm_name: "Pure-SE-Lab-RDS"

# VM Template Creation Pipeline
# Tracks the full lifecycle: Candidate VMs → Source Templates → Content Library OVAs
vm_template_pipeline:
  
  # Infrastructure Configuration
  infrastructure:
    vcenter_folder: "pstg-template"           # vCenter folder for source templates
    content_library: "mel-au-lab"            # Content library for final OVAs
    repository: "prosham-purestorage/se-lab-melau-vmtemplates"
    
  # Template Creation Workflow
  # 1. Candidate VMs: Running VMs used for installation and customization
  # 2. Source Templates: Cleaned up VMs ready for templating (in vCenter folder)
  # 3. Content Library OVAs: Final packaged templates for deployment
  
  candidate_vms:
    # Ubuntu Candidates - Running VMs for installation/customization
    ubuntu_2204_candidate:
      vm_name: "pstg-ubuntu-2204-candidate"
      base_iso: "ubuntu-22.04.4-live-server-amd64.iso"
      cpu_cores: 2
      memory_gb: 4
      disk_gb: 20
      network: "MgmtDPG"
      status: "active"                        # active, building, completed
      install_scripts:
        - "ubuntu-base-install.sh"
        - "ubuntu-domain-join.sh"
        - "ubuntu-security-hardening.sh"
        - "ubuntu-monitoring-setup.sh"
      customization_scripts:
        - "install-docker.sh"
        - "install-ansible.sh"
        - "configure-ssh-keys.sh"
        - "install-pure-tools.sh"
      
    ubuntu_2404_candidate:
      vm_name: "pstg-ubuntu-2404-candidate"
      base_iso: "ubuntu-24.04.1-live-server-amd64.iso"
      cpu_cores: 2
      memory_gb: 4
      disk_gb: 20
      network: "MgmtDPG"
      status: "planned"
      install_scripts:
        - "ubuntu-base-install.sh"
        - "ubuntu-domain-join.sh"
        - "ubuntu-security-hardening.sh"
        - "ubuntu-monitoring-setup.sh"
      customization_scripts:
        - "install-docker.sh"
        - "install-ansible.sh"
        - "configure-ssh-keys.sh"
        - "install-pure-tools.sh"
    
    # Windows Candidates
    windows_2022_candidate:
      vm_name: "pstg-windows-2022-candidate"
      base_iso: "windows-server-2022-datacenter.iso"
      cpu_cores: 4
      memory_gb: 8
      disk_gb: 60
      network: "MgmtDPG"
      status: "planned"
      install_scripts:
        - "windows-base-install.ps1"
        - "windows-domain-join.ps1"
        - "windows-security-config.ps1"
      customization_scripts:
        - "install-chocolatey.ps1"
        - "install-powershell-modules.ps1"
        - "configure-winrm.ps1"
        - "install-pure-tools.ps1"
  
  source_templates:
    # Source Templates in vCenter folder - cleaned and ready for OVA export
    ubuntu_2204_single_homed:
      template_name: "ubuntu-2204-single-net-template"
      source_candidate: "ubuntu_2204_candidate"
      network_type: "single_homed"
      network_config:
        primary_adapter: "vmxnet3"
        primary_network: "MgmtDPG"
        dhcp_enabled: true
        static_capable: true
      preparation_steps:
        - "cleanup-logs"
        - "reset-network-config"
        - "clear-ssh-keys"
        - "sysprep-linux"
      status: "ready"                         # building, ready, exported
      
    ubuntu_2204_dual_homed:
      template_name: "ubuntu-2204-dual-net-template"
      source_candidate: "ubuntu_2204_candidate"
      network_type: "dual_homed"
      network_config:
        primary_adapter: "vmxnet3"
        secondary_adapter: "vmxnet3"
        management_network: "MgmtDPG"
        storage_network: "StorageDPG"
        dhcp_enabled: true
        static_capable: true
      preparation_steps:
        - "cleanup-logs"
        - "configure-dual-network"
        - "reset-network-config"
        - "clear-ssh-keys"
        - "sysprep-linux"
      status: "building"
      
    ubuntu_2404_single_homed:
      template_name: "ubuntu-2404-single-net-template"
      source_candidate: "ubuntu_2404_candidate"
      network_type: "single_homed"
      network_config:
        primary_adapter: "vmxnet3"
        primary_network: "MgmtDPG"
        dhcp_enabled: true
        static_capable: true
      preparation_steps:
        - "cleanup-logs"
        - "reset-network-config"
        - "clear-ssh-keys"
        - "sysprep-linux"
      status: "planned"
      
    windows_2022_single_homed:
      template_name: "windows-2022-single-net-template"
      source_candidate: "windows_2022_candidate"
      network_type: "single_homed"
      network_config:
        primary_adapter: "vmxnet3"
        primary_network: "MgmtDPG"
        dhcp_enabled: true
        static_capable: true
      preparation_steps:
        - "cleanup-temp-files"
        - "reset-network-config"
        - "clear-event-logs"
        - "sysprep-windows"
      status: "planned"
  
  content_library_ovas:
    # Final OVAs in Content Library - ready for deployment
    ubuntu_2204_base:
      ova_name: "ubuntu-2204-base.ova"
      source_template: "ubuntu_2204_single_homed"
      description: "Ubuntu 22.04 LTS base template with Pure Storage tools"
      version: "1.0.0"
      last_updated: "2025-08-03"
      network_support: ["single_homed"]
      use_cases: ["development", "testing", "general workloads"]
      status: "active"                        # active, deprecated, archived
      
    ubuntu_2204_dual:
      ova_name: "ubuntu-2204-dual.ova"
      source_template: "ubuntu_2204_dual_homed"
      description: "Ubuntu 22.04 LTS dual-homed template for storage workloads"
      version: "1.0.0"
      last_updated: "2025-08-03"
      network_support: ["dual_homed"]
      use_cases: ["production", "storage systems", "performance testing"]
      status: "building"
      
    ubuntu_2404_base:
      ova_name: "ubuntu-2404-base.ova"
      source_template: "ubuntu_2404_single_homed"
      description: "Ubuntu 24.04 LTS base template with Pure Storage tools"
      version: "1.0.0"
      last_updated: "2025-08-03"
      network_support: ["single_homed"]
      use_cases: ["development", "testing", "latest features"]
      status: "planned"
      
    windows_2022_base:
      ova_name: "windows-2022-base.ova"
      source_template: "windows_2022_single_homed"
      description: "Windows Server 2022 base template with Pure Storage tools"
      version: "1.0.0"
      last_updated: "2025-08-03"
      network_support: ["single_homed"]
      use_cases: ["windows workloads", "active directory", "file services"]
      status: "planned"

# Legacy VM Templates (maintained for backward compatibility)
vm_templates:
  ubuntu:
    template_name: "pr-ubuntu-template"
    base_image: "Ubuntu 22.04 LTS"
    cpu_cores: 2
    memory_gb: 4
    disk_gb: 20
    network: "VM Network"
    repository: "prosham-purestorage/se-lab-melau-vmtemplates"
    
    # Network Configuration Options
    network_configurations:
      single_homed:
        name_suffix: "single-net"
        primary_network: "MgmtPG"
        description: "Single network adapter for management traffic only"
        use_cases: ["development", "testing", "simple deployments"]
        
        # Network configuration capabilities
        network_config:
          dhcp_enabled: true        # Default to DHCP
          static_capable: true      # Can be overridden at deployment
          adapter_type: "vmxnet3"
          
      dual_homed:
        name_suffix: "dual-net"
        primary_network: "VMnetPG"      # Management network
        secondary_network: "StoragePG"   # Storage network  
        description: "Dual network adapters for management and storage separation"
        use_cases: ["production", "storage systems", "performance testing"]
        
        # Network configuration capabilities
        network_config:
          management_dhcp: true     # Management network defaults to DHCP
          storage_dhcp: true        # Storage network defaults to DHCP
          static_capable: true      # Can be overridden at deployment
          adapter_type: "vmxnet3"
        
    # Template Variants by Ubuntu Version
    variants:
      ubuntu_20_04:
        base_image: "Ubuntu 20.04 LTS"
        support_level: "maintenance"
      ubuntu_22_04:
        base_image: "Ubuntu 22.04 LTS"
        support_level: "active"
      ubuntu_24_04:
        base_image: "Ubuntu 24.04 LTS"
        support_level: "active"
      
  windows_server:
    template_name: "pr-windows-server-template" 
    base_image: "Windows Server 2022"
    cpu_cores: 4
    memory_gb: 8
    disk_gb: 60
    network: "VM Network"
    repository: "prosham-purestorage/se-lab-melau-vmtemplates"
      
  windows_client:
    template_name: "pr-windows-client-template"
    base_image: "Windows 11 Enterprise"
    cpu_cores: 2
    memory_gb: 8
    disk_gb: 60
    network: "VM Network"
    repository: "prosham-purestorage/se-lab-melau-vmtemplates"

integration:
  repositories:
    config: "https://github.com/prosham-purestorage/se-lab-melau-config"
    webconsole: "https://github.com/prosham-purestorage/se-lab-melau-webconsole"
    vmtemplates: "https://github.com/prosham-purestorage/se-lab-melau-vmtemplates"
    ansible: "https://github.com/prosham-purestorage/se-lab-melau-ansible"
    
  shared_secrets:
    encryption_method: "aes-256-cbc"
    keyfile_location: "$HOME/.purestorage/se-lab-melau.key"
    secrets_file: "secrets.yml.encrypted"

pure_storage:
  arrays:
    primary:
      management_vip: "10.112.0.5"
      username: "pureuser"

# VM Deployments - Specific VM instances with their network configurations
vm_deployments:
  pstg_mgmt_admin:
    content_library_template: "ubuntu-2204-base.ova"
    network_type: "single_homed"
    description: "Primary management admin VM"
    hostname: "pstg-mgmt-admin"
    network:
      management:
        port_group: "MgmtDPG"
        ip_address: "10.112.0.11"
        netmask: "255.255.255.0"
        gateway: "10.112.0.1"
        dns: ["10.112.0.9"]
        domain: "mel.aulab.purestorage.com"
        
  pstg_test_dual:
    content_library_template: "ubuntu-2204-base.ova"
    network_type: "dual_homed"
    description: "Dual-homed test VM for storage testing"
    hostname: "pstg-test-dual"
    network:
      management:
        ip_address: "10.211.0.101"
        netmask: "255.255.255.0"
        gateway: "10.211.0.1"
        dns: ["10.112.0.9"]
      storage:
        ip_address: "10.212.0.101"
        netmask: "255.255.255.0"
        gateway: "10.212.0.1"
        # Storage network typically doesn't need DNS
        
  pstg_mgmt_webconsole:
    content_library_template: "ubuntu-2204-base.ova"
    network_type: "single_homed"
    description: "Web console VM"
    hostname: "pstg-mgmt-webconsole"
    network:
      management:
        ip_address: "10.112.0.10"
        netmask: "255.255.255.0"
        gateway: "10.112.0.1"
        dns: ["10.112.0.9"]
        domain: "mel.aulab.purestorage.com"

security:
  ssl_certificates:
    path: "/opt/vmware-webconsole/certificates"
    auto_renew: true
  
  session:
    timeout_minutes: 480
    max_concurrent: 10

monitoring:
  log_level: "info"
  retention_days: 30