name: Export Configuration

on:
  push:
    branches: [ main ]
    paths:
      - 'lab-config.yml'
      - 'secrets.yml.encrypted'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install PyYAML cryptography

    - name: Export configuration (.env)
      run: python scripts/subscriber/update.py --type env --output export/lab-config.env

    - name: Export configuration (.json)
      run: python scripts/subscriber/update.py --type json --output export/lab-config.json

    - name: Export configuration (PowerShell)
      run: python scripts/subscriber/update.py --type ps1 --output export/vmware-config.ps1
      
    - name: Commit exports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add export/
        if ! git diff --staged --quiet; then
          git commit -m "Auto-export configuration [skip ci]"
          git push
        fi
